### ISSUE TITLE
新版思路

### ISSUE THREAD

**Issue by xuexb** [apijs/apijs#1]
### 前后端分离

这版本想使用 [element-ui](http://element.eleme.io/#/zh-CN) 开发, 她是由`webpack`打包, 所以想的是把后台管理端的前端静态文件(`html`, `css`, `js`, `png`)单独创建一个repo来维护, 我起名叫她为: [apijs-admin](https://github.com/apijs/apijs-admin), 然后在`apijs`内引用这个模块, 并把`^/admin/*`的静态请求代理到这个模块, 而`apijs-admin`只是纯洁的页面, 数据全由`apijs`来提供, 如: `^/admin/api/*`

### 接口如何管理多个状态

一个接口有些时候是需要根据请求的参数来返回不同的数据, 比如登录接口, 想要`mock`出: 请求参数为空、用户名密码错误、登录成功等几个状态, 我想的是: **给返回值使用模板引擎编译**, 并提供一些常用的变量, 比如:

- post.xxx - 获取post的数据
- get.xxx - 获取get的数据
- params.xxx - 获取参数数据, 优先使用get->post

考虑到可能是`jsonp`接口, 并且`callbackName`不定、超时的配置等, 提供一些方法, 比如:

- setCallback(name) - 设置`jsonp`回调名称
- setTimeout(num) - 设置超时时间
- setStatus(status) - 设置接口状态码
- setDataType(str) - 设置接口响应类型

需要注意的是, 这些方法设置的都会覆盖接口编辑的内容~来几个demo:

#### 用户登录

```
{{if !post.username || !post.password}}
    // 响应为空
    {
        errcode: 1,
        errmsg: '用户名或者密码为空'
    }
{{else if post.username === 'xxoo' && post.password === 'xxoo'}}
    // 响应成功
    {
        data: {
            uid: 1
        }
    }
{{else}}
    // 响应错误
    {
        errcode: 2,
        errmsg: '用户名或者密码错误'
    }
{{/if}}
```

#### 设置超时、出错, 测试前端loading和error状态

```
{{if get.time}}
    {{setTimeout(5000)}}

    // 响应成功
    {}

{{else if get.type === 'text'}}
    {{setDataType('text')}}

    // 响应成功
    {}

{{else}}
    {{setStatus(500)}}

    {
        error: 500
    }
{{/if}}
```

> 注: 模板引擎语法只是我模拟的, 具体语法待定

### 如何处理生成文档

因为编辑了接口的各种参数了, 那么就可以把返回值使用模板引擎直接编译出来生成文档, 但问题是**一个接口支持多个状态的返回值**, 那么单纯的编译就不行了, 因为返回内存在条件判断, 因为接口的作者肯定明白返回值的套路, 我想的是由用户手动的维护文档的条件数据, 如刚才的登录接口的文档条件数据为:

```json
[
    {
        "name": "用户名或密码为空"
    },

    {
        "name": "用户名或密码错误",
        "post": {
            "username": "test",
            "password": "test"
        }
    },

    {
        "name": "登录成功",
        "post": {
            "username": "xxoo",
            "password": "xxoo"
        }
    }
]
```

这样的话可以循环文档条件数据来把参数(post, get, params)透传到返回值内, 从而实现多条件返回值显示

### 接口提供哪些可编辑内容?

1. 接口名称
1. 链接地址 - 不能和内置的接口冲突, 如: `/admin/api/list`(后台中获取列表的接口)
1. 分组 - 提供以分组为维度的列表, 不填进入默认分组, 比如:
    1. 用户接口 - 分组名
        1. 登录 - 接口名
        2. 注册
        3. 退出
    1. 照片相关 - 分组名
        1. 获取照片列表 - 接口名
        2. 添加照片
        3. 删除照片
    1. ...
1. 允许的请求类型 - get,post,delete,put ...
4. 接口参数配置 - 支持必选、参数值类型验证(可枚举类型, 等于, 正则)
1. 返回值的类型 - json, jsonp, text (会根据该选项设置不同的`Content-Type`)
2. 返回值配置 - 由于考虑到一个接口需要处理不同的状态, 返回值使用模板引擎进行编译, 约定几个接口透传的变量对象, 可以根据这些变量返回不同的数据结构. 支持 [mockjs](http://mockjs.com/) 语法
3. 文档数据配置 - 由于考虑到一个接口需要不同状态, 那么单纯的编译不能生成不同的状态, 需要配置不同的数据条件来对应返回值
4. 超时时间 - 可以配置接口响应时间
5. 返回状态 - http.status

### 使用成本

由于只是提供`web`端接口管理, 还是需要用户去维护代码片段, 并且文档条件数据编辑那不是很容易理解, 如果接口要不考虑多条件情况就简单多了, 但又要舍弃很多功能...

**Comment by yugasun** [comment]
接口如何管理多个状态，我觉得基于json配置，比较合适，如对于用户登录接口 /api/user/login, 根据接口名称，读取相应的接口配置文件 `user.login.config.json` 内容如下，对于接口params直接就是接口字段配置，返回值也可以定制化，对于一些定制数据，可以直接依赖  [mockjs](http://mockjs.com/) 生成，不必重新再造轮子。

```javascript
[
  {
    method: 'post',
    params: {
      username: {
        text: '用户名',
        type: 'string',
        required: true,
      },
      password: {
        text: '密码',
        type: 'string',
        required: true,
      }
    },
    results: [   // 返回结果列表
      {
        condition: { // 判定条件，模式待定
          username: 'admin',
          password: 'admin',
        },
        return: {
          errcode: 0,
          msg: '登录成功',
          data: {
            uid: 1,
            ...
          }
        }
      },
      {
        condition: {
          username: '',
          password: '',
        },
        return: {
          errcode: 1,
          msg: '用户名或者密码为空'
        }
      },
      {
        condition: {
          username: 'test',
          password: 'test',
        },
        return: {
          errcode: 2,
          msg: '用户名或密码错误'
        }
      }
    ]
  }
]
```

**Comment by xuexb** [comment]
@yugasun 额, 你这个跟 [https://github.com/mobejs/mobe](https://github.com/mobejs/mobe) 好像

**Comment by xuexb** [comment]
mobe的思路就是全由前端代码编写, 然后自动生成, 没有平台化编辑

**Comment by yugasun** [comment]
mobe没看过，不过还是需要平台化编辑，通过平台化编辑，生成相应的配置文件，然后apijs调用，在此基础上生成相应的接口文档。作为大前端，我们尽量都用js来写吧，实在没法解决的，你上~，其他语言我不太擅长，囧~

**Comment by xuexb** [comment]
由于和新版思路变动很大, 特开 #2
